server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8080
  connection-timeout: 5000ms

spring:
  application:
    name: base-boot
  profiles:
    active: dev



##mybatis-plus mapper xml 文件地址
mybatis-plus:
  mapper-locations: classpath*:mapper/*/*Mapper.xml
  ##mybatis-plus type-aliases 文件地址
  type-aliases-package: com.donger.baseboot.modules.*.entity
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: AUTO

---

spring:
  profiles: dev
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:114.115.133.57}:${MYSQL_PORT:3306}/boot_admin?characterEncoding=utf8&useSSL=false
    username: admin
    password: ${MYSQL_ROOT_PASSWORD:COM.donger.7326}
    driver-class-name: com.mysql.cj.jdbc.Driver